name: Build and Package TeachConnect-neo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Build type (Release/Debug)'
        required: false
        default: 'Release'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-
          ${{ runner.os }}-python-
          ${{ runner.os }}-

    - name: Cache Nuitka Dependency Walker
      uses: actions/cache@v4
      with:
        path: C:\Users\runneradmin\AppData\Local\Nuitka\Nuitka\Cache\downloads\depends\x86_64
        key: ${{ runner.os }}-nuitka-depends-cache-v1
        restore-keys: |
          ${{ runner.os }}-nuitka-depends-cache-
      env:
        NUITKA_DOWNLOAD_DEPENDS: "yes"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with Nuitka
      uses: Nuitka/Nuitka-Action@v1.2
      with:
        script-name: main.py
        output-file: TeachConnect-neo.exe  # 输出文件名应包含 .exe 扩展名
        onefile: true  # 如果您希望生成一个单独的可执行文件，设置为 true
        standalone: true
        windows-icon-from-ico: icon.ico  # 使用 .ico 格式的图标文件
        include-data-dir: |
          assets=assets  # 包含 assets 文件夹及其内容
          pages=pages  # 包含 pages 文件夹及其内容
        enable-plugins: pyside6  # 使用小写的插件名称
        windows-console-mode: attach
        nofollow-import-to: test

    - name: Zip the build artifact
      run: |
        if (Test-Path -Path '.\build\main.dist\*') {
          dir '.\build\main.dist\*'
          Compress-Archive -Path '.\build\main.dist\*' -DestinationPath 'TeachConnect-neo_build-windows-latest.zip' -Force
        } else {
          Write-Error "Build artifact not found in .\build\main.dist\*"
        }

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: TeachConnect-neo_build-Windows-latest.zip
        path: TeachConnect-neo_build-windows-latest.zip
